blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/ilker-binzet/SunoReady/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📚 Documentation
    url: https://github.com/ilker-binzet/SunoReady/blob/main/README.md
    about: Check out the documentation and guides
  - name: 🔧 Troubleshooting
    url: https://github.com/ilker-binzet/SunoReady/blob/main/docs/SUNO_BYPASS_GUIDE.md
    about: Common issues and troubleshooting guide
